### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [FabienSerny/sellermania-prestashop#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by FabienSerny** [comment]
Hi Karan,
I will add a Readme, however licence is already written in all source files, so in this case, it's not really a problem :)

**Comment by FabienSerny** [comment]
License has been added
