### ISSUE TITLE
SellermaniaOrderConfirmation::confirmOrderItems ?

### ISSUE THREAD

**Issue by Doc0160** [FabienSerny/sellermania-prestashop#3]
SellermaniaDisplayAdminOrderController uses SellermaniaOrderConfirmation::confirmOrderItems which does not exist.

[See here](https://github.com/FabienSerny/sellermania-prestashop/blob/6e512f12ff9749779c560d3b671a090b731624f4/controllers/hook/SellermaniaDisplayAdminOrder.php#L103)

**Comment by FabienSerny** [comment]
Hi,

This problems was already solved on development branch.
I just push it to master :)

Best
