### ISSUE TITLE
Use Carrier::ALL_CARRIERS

### ISSUE THREAD

**Issue by Doc0160** [FabienSerny/sellermania-prestashop#4]
Why put a 5 [here](https://github.com/FabienSerny/sellermania-prestashop/blob/6e512f12ff9749779c560d3b671a090b731624f4/controllers/hook/SellermaniaGetContent.php#L192) ?
Prestashop provides a const for that. Would make the code a little more understandable.
[PS 1.4](https://github.com/PrestaShop/PrestaShop-1.4/blob/master/classes/Carrier.php#L36)
[PS 1.5](https://github.com/PrestaShop/PrestaShop-1.5/blob/master/classes/Carrier.php#L36)
[PS 1.6](https://github.com/PrestaShop/PrestaShop/blob/master/classes/Carrier.php#L35)

**Comment by FabienSerny** [comment]
Hi,

This constant does not exists in all PS 1.4 version.
Check for example PS 1.4.3 Carrier Classes

**Comment by FabienSerny** [comment]
In fact, this constant exists as a define in 1.4.3 (in defines.inc.php) so I would have to add an extra on version to make it work. I'll rather let 5 (and make a comment above)

**Comment by FabienSerny** [comment]
https://github.com/FabienSerny/sellermania-prestashop/commit/1ef40d2eb9f310aaf5fe40ea4ed1be7159a2d040
