### ISSUE TITLE
id_tax always set to 0

### ISSUE THREAD

**Issue by Doc0160** [FabienSerny/sellermania-prestashop#5]
The id_tax in a project I'm working on should be 1. 
Should't the id_tax be loaded from somewhere ? 
Any workaround before editing the module myself ?
[Here](https://github.com/FabienSerny/sellermania-prestashop/blob/6e512f12ff9749779c560d3b671a090b731624f4/controllers/hook/SellermaniaImportOrder.php#L836)

**Comment by FabienSerny** [comment]
Hi,

This problem was already solved on development branch.
I just push it to master.

Thanks for all your others contributions :)
