### ISSUE TITLE
Duplicate Payments

### ISSUE THREAD

**Issue by Doc0160** [FabienSerny/sellermania-prestashop#6]
When importing from Sellermania, I sometimes end up with 2 payments (exact copy of each other). Any idea why ?
PrestaShop 1.5.6.1, module Sellermania 2.0.7

**Comment by FabienSerny** [comment]
Do you have two payments or two status "Payment accepted" ?
In the first case, no one reported me this issue until now, do you have more detailed about it ?
If it's the second case, the problem has been solved with the last version.

Please upgrade to 2.1.7 and tell me if the problem is still here

**Comment by FabienSerny** [comment]
Since, I had no news on this, I'm closing this issue.
